---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
services:
  app:
    build: .
    ports:
      - 8501:8501
    restart: always
    depends_on:
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    networks:
      - ollama-docker
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker
    healthcheck:
      test: ["CMD-SHELL", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  ollama-init:
    image: ollama/ollama:latest
    entrypoint:
      [
        "bash",
        "-c",
        "for model in mxbai-embed-large llama3.2 deepseek-coder; do ollama pull $$model; done",
      ]
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - ollama
    networks:
      - ollama-docker
networks:
  ollama-docker:
    external: false
